image: greut/texlive-full

variables:
  PANDOC_VERSION: "2.12"
  PANDOC_CROSSREF_VERSION: "0.3.10.0"

stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - "*.pdf"
  script:
  - apt-get update -q
  - apt-get install -qy
    curl
    fonts-croscore
    fonts-crosextra-carlito
    fonts-inconsolata
    fonts-texgyre
    lmodern
    tex-gyre
    xz-utils
  - curl --fail --remote-name -L
    https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}-1-amd64.deb
  - dpkg -i pandoc-${PANDOC_VERSION}-1-amd64.deb
  - curl --fail --remote-name -L
    https://github.com/lierdakil/pandoc-crossref/releases/download/v${PANDOC_CROSSREF_VERSION}/pandoc-crossref-Linux.tar.xz
  - tar xf pandoc-crossref-Linux.tar.xz
  - mv pandoc-crossref /usr/local/bin
  - make all

pages:
  stage: deploy
  dependencies:
    - build
  artifacts:
    paths:
      - public
  only:
    - master
  script: |
    (
      mkdir public
      cp *.pdf public
      cd public
      echo '<!DOCTYPE html><meta charset=utf-8><title>Rapport Technique</title>' > index.html
      echo '<h1>Télécharger le rapport technique</h1>' >> index.html
      echo '<p>Styles</p><ul>' >> index.html
      echo '<li><a href="rapport.pdf">Koma + Linux Libertine</a>' >> index.html
      echo '<li><a href="rapport-cros.pdf">Koma + Chrome OS</a>' >> index.html
      echo '<li><a href="rapport-gyre.pdf">Simple + TeX Gyre</a>' >> index.html
    )
