dist: trusty
sudo: required

language: generic

cache: apt

env:
  global:
    - PANDOC_VERSION=2.1.3
    - PANDOC_CROSSREF_VERSION=0.3.1.0

addons:
  apt:
    packages:
      - latex-xcolor
      - lmodern
      - make
      - texlive-fonts-extra
      - texlive-fonts-recommended
      - texlive-lang-french
      - texlive-latex-extra
      - texlive-math-extra
      - texlive-xetex

install:
  - wget https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}-1-amd64.deb -O pandoc.deb
  - sudo dpkg -i pandoc.deb
  - wget https://github.com/lierdakil/pandoc-crossref/releases/download/v${PANDOC_CROSSREF_VERSION}/linux-ghc8-pandoc-2-1.tar.gz
  - tar xf linux-ghc82-pandoc-2-1.tar.gz
  - sudo mv pandoc-crossref /usr/local/bin

script:
  - make all

after_success:
  - >
    test "${TRAVIS_PULL_REQUEST}" = "false" \
      && test "${TRAVIS_BRANCH}" = "master" \
      && ( \
        mkdir build
        cp rapport.pdf build
        cd build
        echo '<!DOCTYPE html><title>Rapport Technique</title><h1><a href="rapport.pdf">Télécharger le rapport technique</a> (PDF)</h1>' > index.html
        echo '<a href="https://github.com/HE-Arc/rapport-technique"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/a6677b08c955af8400f44c6298f40e7d19cc5b2d/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677261795f3664366436642e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png"></a>' >> index.html
        git init
        git config user.name "TravisCI"
        git config user.email "travis@he-arc.test"
        git add .
        git commit -m "Deployed to github pages"
        git push -f -q "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}" master:gh-pages
      ) \
      || echo ":-)"
